insert into contatos(assunto,mensagem,cliente_id_fk) values ('Jewelry', 'Destruction of Left Main Bronchus, Perc Endo Approach', 1),
('Baby', 'Destruction of Thoracic Vertebra, Percutaneous Approach', 2),
('Clothing', 'Bypass R Popl Art to Peron Art with Synth Sub, Open Approach', 3),
('Home', 'Repair Left Temporomandibular Joint, Perc Endo Approach', 4),
('Health', 'Dilation of R Brach Art with 2 Drug-elut, Open Approach', 5),
('Sports', 'Restriction of Left Hand Vein, Perc Endo Approach', 6),
('Grocery', 'Extraction of Lumbar Nerve, Open Approach', 7),
('Music', 'Revision of Spacer in L Metatarsophal Jt, Perc Endo Approach', 8),
('Health', 'CT Scan of Renal Art Transplant using Oth Contrast', 9),
('Sports', 'Insertion of Endobronchial Valve into Lingula Bronchus, Endo', 10),
('Automotive', 'Repair Thymus, Percutaneous Approach', 11),
('Home', 'Removal of Neuro Lead from Cranial Nrv, Perc Approach', 12),
('Outdoors', 'Replacement of L Lacrml Duct with Autol Sub, Via Opening', 13),
('Industrial', 'Dilate L Popl Art, Bifurc, w 2 Drug-elut, Open', 14),
('Electronics', 'Revision of Spacer in R Metatarsophal Jt, Open Approach', 15),
('Tools', 'Excision of Right Vas Deferens, Perc Endo Approach, Diagn', 16),
('Music', 'Replacement of Left Eye with Autol Sub, Perc Approach', 17),
('Home', 'Reposition Left Cephalic Vein, Percutaneous Approach', 18),
('Sports', 'Removal of Traction Apparatus on Left Lower Leg', 19),
('Health', 'Introduction of Oth Anti-infect into Low GI, Perc Approach', 20),
('Industrial', 'Revision of Int Fix in R Finger Phalanx Jt, Extern Approach', 21),
('Toys', 'Dilation of Upper Artery with 2 Drug-elut, Perc Approach', 22),
('Games', 'Reattachment of Left Hand Tendon, Perc Endo Approach', 23),
('Music', 'Occlusion of Right Spermatic Cord, Perc Endo Approach', 24),
('Outdoors', 'Magnetic Resonance Imaging (MRI) of Bilateral Renal Arteries', 25),
('Health', 'Replace L Ear Skin w Autol Sub, Full Thick, Extern', 26),
('Toys', 'Destruction of Left Internal Carotid Artery, Perc Approach', 27),
('Jewelry', 'Fusion of Lum Jt, Post Appr A Col, Perc Endo Approach', 28),
('Electronics', 'Dilation of R Hand Art with 2 Drug-elut, Perc Approach', 29),
('Clothing', 'Drainage of Chest Wall, Percutaneous Endoscopic Approach', 30),
('Shoes', 'Removal of Radioact Elem from Pericard Cav, Open Approach', 31),
('Outdoors', 'Drainage of Left Subclavian Vein, Perc Approach, Diagn', 32),
('Home', 'Removal of Int Fix from R Elbow Jt, Extern Approach', 33),
('Games', 'MRI of R Breast using Oth Contrast, Unenh, Enhance', 34),
('Shoes', 'Change Bandage on Right Inguinal Region', 35),
('Games', 'Remove Infusion Dev from Prostate/Seminal Ves, Open', 36),
('Games', 'Fusion Cerv Jt w Synth Sub, Post Appr P Col, Perc', 37),
('Health', 'Removal of Synth Sub from R Hip Jt, Perc Endo Approach', 38),
('Clothing', 'Reposition Left Toe Phalanx with Ext Fix, Perc Endo Approach', 39),
('Beauty', 'Drainage of Left Mastoid Sinus, Perc Endo Approach', 40),
('Outdoors', 'Bypass L Ext Iliac Art to L Femor A w Nonaut Sub, Perc Endo', 41),
('Kids', 'Dilation of 2 Cor Art with 3 Drug-elut, Perc Endo Approach', 42),
('Sports', 'Dilate L Renal Art, Bifurc, w 3 Drug-elut, Perc Endo', 43),
('Outdoors', 'Reposition Cerv Jt with Int Fix, Perc Approach', 44),
('Grocery', 'Removal of Synth Sub from Up Muscle, Perc Endo Approach', 45),
('Sports', 'Release Head and Neck Tendon, Perc Endo Approach', 46),
('Jewelry', 'Release R Low Extrem Bursa/Lig, Perc Endo Approach', 47),
('Computers', 'Occlusion Mesenteric Lymph w Extralum Dev, Open', 48),
('Games', 'Insert of Hybrid Ext Fix into R Humeral Shaft, Open Approach', 49),
('Shoes', 'Revision of Intraluminal Device in Right Eye, Open Approach', 50),
('Outdoors', 'Repair Left Upper Extremity, Percutaneous Approach', 51),
('Books', 'Occlusion of L Innom Vein with Intralum Dev, Open Approach', 52),
('Clothing', 'Drainage of Brain, Percutaneous Endoscopic Approach', 53),
('Jewelry', 'Revision of Infusion Device in R Low Extrem, Extern Approach', 54),
('Books', 'Removal of Nonaut Sub from Skull, Perc Endo Approach', 55),
('Computers', 'Destruction of Right Finger Phalanx, Percutaneous Approach', 56),
('Kids', 'Destruction of Right Knee Bursa and Ligament, Open Approach', 57),
('Health', 'Drainage of Left Ankle Tendon with Drain Dev, Open Approach', 58),
('Sports', 'Plain Radiography of R Ext Carotid using Oth Contrast', 59),
('Health', 'Reposition Left Lower Femur with Ring Ext Fix, Open Approach', 60),
('Clothing', 'Drainage of Acoust Nrv with Drain Dev, Perc Endo Approach', 61),
('Baby', 'Dilate 4+ Cor Art, Bifurc, w Intralum Dev, Open', 62),
('Toys', 'Dilate R Int Iliac Art, Bifurc, w 2 Drug-elut, Open', 63),
('Sports', 'Supplement Hyoid Bone with Autol Sub, Perc Endo Approach', 64),
('Kids', 'Bypass L Com Carotid to Intracran Art w Autol Vn, Open', 65),
('Baby', 'Replacement of R Low Eyelid with Nonaut Sub, Perc Approach', 66),
('Movies', 'Bypass Sup Vena Cava to Pulm Vn Cnfl w Zooplastic, Perc Endo', 67),
('Computers', 'Reposition Left Vertebral Vein, Percutaneous Approach', 68),
('Clothing', 'Removal of Monitor Dev from Trachea, Perc Endo Approach', 69),
('Tools', 'Drain of Cereb Meninges with Drain Dev, Perc Endo Approach', 70),
('Movies', 'Revision of Synth Sub in Up Art, Perc Endo Approach', 71),
('Kids', 'Plain Radiography of L Up Extrem Lymph using L Osm Contrast', 72),
('Electronics', 'Revision of Int Fix in L Metatarsophal Jt, Perc Approach', 73),
('Garden', 'Replace L Foot Skin w Synth Sub, Full Thick, Extern', 74),
('Games', 'Extraction of Left Wrist Bursa and Ligament, Open Approach', 75),
('Garden', 'Release Upper Artery, Percutaneous Approach', 76),
('Toys', 'Repair Mesenteric Lymphatic, Open Approach', 77),
('Industrial', 'Extirpation of Matter from Lower Artery, Perc Endo Approach', 78),
('Computers', 'Excision of Pharynx, Via Opening, Diagn', 79),
('Electronics', 'Extirpate matter from R Int Iliac Art, Bifurc, Open', 80),
('Beauty', 'Bypass L Brach Art to L Up Arm Art w Autol Art, Open', 81),
('Games', 'Dilation of Left Ulnar Artery, Percutaneous Approach', 82),
('Garden', 'Excision of Right Testis, Percutaneous Approach', 83),
('Garden', 'Drainage of Right Metacarpal, Percutaneous Approach', 84),
('Electronics', 'Excision of Nasal Septum, Open Approach, Diagnostic', 85),
('Kids', 'Restriction of Right Thyroid Artery, Percutaneous Approach', 86),
('Tools', 'Destruction of Right Hand Vein, Perc Endo Approach', 87),
('Jewelry', 'Computerized Tomography (CT Scan) of Mandible', 88),
('Beauty', 'Dilation of Left Hepatic Duct with Intraluminal Device, Endo', 89),
('Grocery', 'Reattachment of Left Main Bronchus, Open Approach', 90),
('Industrial', 'Drainage of R Low Extrem with Drain Dev, Open Approach', 91),
('Grocery', 'Removal of Autol Sub from Low Intest Tract, Open Approach', 92),
('Books', 'Bypass L Int Iliac Art to Foot Art, Perc Endo Approach', 93),
('Health', 'Introduction of Other Gas into Lower GI, Via Opening', 94),
('Outdoors', 'Inspection of Left Hand, Percutaneous Approach', 95),
('Kids', 'Removal of Drainage Device from Adrenal Gland, Perc Approach', 96),
('Games', 'Restriction of Low Art with Intralum Dev, Perc Endo Approach', 97),
('Music', 'Fusion of R Tarsal Jt with Ext Fix, Perc Endo Approach', 98),
('Music', 'Drainage of Right Lobe Liver, Percutaneous Approach, Diagn', 99),
('Industrial', 'Bypass 2 Cor Art from Abd Art with Autol Vn, Open Approach', 100),
('Automotive', 'Inspection of Left Hand, Open Approach', 101),
('Movies', 'Extirpation of Matter from Penis, Percutaneous Approach', 102),
('Jewelry', 'Excision of L Low Arm & Wrist Tendon, Open Approach, Diagn', 103),
('Health', 'Bypass Innom Art to Bi Low Arm Art w Autol Art, Open', 104),
('Health', 'Drain of Sup Mesent Vein with Drain Dev, Perc Endo Approach', 105),
('Baby', 'Repair Right 5th Toe, Percutaneous Endoscopic Approach', 106),
('Beauty', 'Excision of Prostate, Percutaneous Approach', 107),
('Music', 'Beam Radiation of Gallbladder using Neutrons', 108),
('Automotive', 'Supplement L Up Extrem Lymph with Synth Sub, Open Approach', 109),
('Electronics', 'Transfer Olfactory Nerve to Abducen Nrv, Perc Endo Approach', 110),
('Shoes', 'Restrict R Kidney Pelvis w Intralum Dev, Perc Endo', 111),
('Toys', 'Imaging, Anatomical Regions, Ultrasonography', 112),
('Games', 'Drain of L Ext Iliac Art with Drain Dev, Perc Endo Approach', 113),
('Industrial', 'Drainage of Left Carpal Joint, Perc Endo Approach', 114),
('Music', 'Extirpation of Matter from Basal Ganglia, Perc Endo Approach', 115),
('Baby', 'Excision of Splenic Vein, Open Approach, Diagnostic', 116),
('Clothing', 'Revision of Int Fix in R Metatarsal, Extern Approach', 117),
('Health', 'Removal of Drain Dev from L Metacarpophal Jt, Open Approach', 118),
('Computers', 'Repair Tongue, Percutaneous Approach', 119),
('Outdoors', 'Removal of Radioactive Element from Pleura, Extern Approach', 120),
('Home', 'Drainage of Splenic Vein, Open Approach, Diagnostic', 121),
('Baby', 'High Dose Rate (HDR) Brachytherapy of Mouth using Cesium 137', 122),
('Books', 'Supplement L Femoral Region w Autol Sub, Perc Endo', 123),
('Beauty', 'Transfuse of Embr Stem Cell into Periph Vein, Open Approach', 124),
('Movies', 'Insertion of Radioact Elem into L Up Leg, Perc Endo Approach', 125),
('Garden', 'Alteration of Bi Ext Ear with Synth Sub, Open Approach', 126),
('Computers', 'Drainage of Right Lower Lobe Bronchus, Perc Endo Approach', 127),
('Toys', 'Supplement Nasopharynx with Nonaut Sub, Via Opening', 128),
('Electronics', 'Insertion of Intralum Dev into L Femor Vein, Open Approach', 129),
('Toys', 'Drainage of L Sup Parathyroid, Perc Endo Approach', 130),
('Computers', 'Transfer Tibial Nerve to Sciatic Nerve, Perc Endo Approach', 131),
('Sports', 'Swallow Dysfunction Treatment using Augment Comm Equipment', 132),
('Automotive', 'Release Right External Jugular Vein, Open Approach', 133),
('Shoes', 'Fluoroscopy of Intracranial Sinuses using H Osm Contrast', 134),
('Sports', 'Removal of Nonaut Sub from R Ulna, Open Approach', 135),
('Automotive', 'Reposition Left Mandible with Ext Fix, Perc Endo Approach', 136),
('Shoes', 'Insertion of Infusion Dev into L Ext Carotid, Perc Approach', 137),
('Games', 'Detachment at Right Ring Finger, Mid, Open Approach', 138),
('Industrial', 'Repair Glomus Jugulare, Percutaneous Endoscopic Approach', 139),
('Health', 'Resection of Right Lower Leg Tendon, Perc Endo Approach', 140),
('Outdoors', 'Drainage of Right Common Carotid Artery, Open Approach', 141),
('Home', 'Extirpation of Matter from Right Trunk Muscle, Open Approach', 142),
('Garden', 'Transfuse of Nonaut Factor IX into POC, Circ, Perc Approach', 143),
('Electronics', 'Supplement Tricusp Valve fr R AV Vlv w Zooplastic, Open', 144),
('Sports', 'Extirpation of Matter from Anal Sphincter, Open Approach', 145),
('Games', 'Drainage of Lower Vein, Percutaneous Endoscopic Approach', 146),
('Clothing', 'Repair Left Metacarpophalangeal Joint, Open Approach', 147),
('Grocery', 'Dilate R Verteb Art, Bifurc, w 4+ Intralum Dev, Open', 148),
('Health', 'Change Other Device on Back', 149),
('Kids', 'Peripheral Nervous System, Supplement', 150),
('Electronics', 'Release Left Diaphragm, Open Approach', 151),
('Baby', 'Revision of Extraluminal Device in Kidney, External Approach', 152),
('Games', 'Extirpation of Matter from Left Upper Femur, Open Approach', 153),
('Sports', 'Division of Left Fibula, Percutaneous Approach', 154),
('Clothing', 'Bypass L Fem Art to Post Tib Art, Perc Endo Approach', 155),
('Industrial', 'HDR Brachytherapy of Brain Stem using Californium 252', 156),
('Movies', 'Release Tongue, Palate, Pharynx Muscle, Perc Endo Approach', 157),
('Automotive', 'Restrict L Int Carotid w Intralum Dev, Perc Endo', 158),
('Grocery', 'Release Inferior Vena Cava, Open Approach', 159),
('Shoes', 'Supplement L Popl Art with Nonaut Sub, Perc Approach', 160),
('Kids', 'Replacement of R Metatarsal with Nonaut Sub, Open Approach', 161),
('Games', 'Removal of Autol Sub from L Shoulder Jt, Open Approach', 162),
('Books', 'Dilation of Left Internal Iliac Artery, Perc Approach', 163),
('Jewelry', 'Release Upper Esophagus, Open Approach', 164),
('Home', 'Revision of Int Fix in L Patella, Extern Approach', 165),
('Books', 'Supplement Ulnar Nerve with Autol Sub, Perc Endo Approach', 166),
('Toys', 'Extirpation of Matter from L Verteb Vein, Perc Endo Approach', 167),
('Clothing', 'Excision of Right Hand Muscle, Perc Endo Approach', 168),
('Jewelry', 'Introduce Oth Anti-infect in Skin/Mucous Mem, Extern', 169),
('Industrial', 'Bypass 2 Cor Art from R Int Mammary w Zooplastic, Open', 170),
('Sports', 'Motor Functn Trmt Integu Low Back/LE w Assist Equip', 171),
('Computers', 'Removal of Infusion Device from L Up Extrem, Extern Approach', 172),
('Kids', 'Destruction of Hyoid Bone, Percutaneous Approach', 173),
('Kids', 'Extirpate matter from L Low Leg Muscle, Perc Endo', 174),
('Baby', 'Bypass Esophagus to Duodenum, Endo', 175),
('Jewelry', 'Excision of Left Common Iliac Artery, Perc Approach, Diagn', 176),
('Music', 'Excision of Lumbar Nerve, Open Approach, Diagnostic', 177),
('Home', 'Bypass R Ventricle to Pulm Trunk w Synth Sub, Open', 178),
('Movies', 'Occlusion of Lower Artery, Open Approach', 179),
('Games', 'Dilation of L Verteb Vein with Intralum Dev, Perc Approach', 180),
('Health', 'Bypass L Great Saphenous to Low Vein w Autol Sub, Perc Endo', 181),
('Baby', 'Insertion of Infusion Dev into R Elbow, Perc Endo Approach', 182),
('Outdoors', 'Restrict Lingula Bronc w Intralum Dev, Perc Endo', 183),
('Movies', 'Occlusion L Int Carotid w Extralum Dev, Perc Endo', 184),
('Games', 'Excision of Inferior Mesenteric Artery, Open Approach, Diagn', 185),
('Outdoors', 'Dilate Sup Vena Cava w Drug-elut Intra, Perc Endo', 186),
('Health', 'Fluoroscopy of Other Veins using Other Contrast, Guidance', 187),
('Sports', 'Reposition Right Ethmoid Bone, External Approach', 188),
('Grocery', 'Drainage of Trochlear Nerve, Perc Endo Approach, Diagn', 189),
('Kids', 'Stereotactic Particulate Radiosurgery of Bladder', 190),
('Beauty', 'Inspection of Products of Conception, Open Approach', 191),
('Health', 'Bypass Left Brachial Artery to Upper Arm Vein, Open Approach', 192),
('Baby', 'Bypass Jejunum to Anus with Autol Sub, Open Approach', 193),
('Computers', 'Removal of Nonaut Sub from R Extraoc Muscle, Open Approach', 194),
('Kids', 'Bypass R Com Iliac Art to Mesent Art w Nonaut Sub, Perc Endo', 195),
('Jewelry', 'Supplement R Zygomatic Bone w Autol Sub, Perc Endo', 196),
('Beauty', 'Supplement Esophageal Vein with Autol Sub, Perc Approach', 197),
('Books', 'Stereotactic Particulate Radiosurgery of Thorax Lymphatics', 198),
('Music', 'Dilate Inf Mesent Art w 3 Intralum Dev, Perc Endo', 199),
('Electronics', 'Restrict L Int Iliac Art w Extralum Dev, Perc Endo', 200),
('Beauty', 'Supplement Right Clavicle with Synth Sub, Open Approach', 201),
('Tools', 'Dilation of Right Subclavian Vein, Open Approach', 202),
('Home', 'Dilate Mid Colic Art, Bifurc, w Drug-elut Intra, Perc Endo', 203),
('Jewelry', 'Occlusion Bi Fallopian Tube w Extralum Dev, Perc', 204),
('Tools', 'Excision of Hymen, Percutaneous Endoscopic Approach', 205),
('Tools', 'Restriction of Ampulla of Vater, Open Approach', 206),
('Music', 'Restrict of R Fem Art with Extralum Dev, Perc Endo Approach', 207),
('Tools', 'Resection of Clitoris, External Approach', 208),
('Games', 'Dilation of Ascending Colon with Intraluminal Device, Endo', 209),
('Jewelry', 'Revision of Synth Sub in Urethra, Perc Endo Approach', 210),
('Jewelry', 'Transfer Accessory Nerve to Trigeminal Nerve, Open Approach', 211),
('Electronics', 'Dilation of R Popl Art with Intralum Dev, Open Approach', 212),
('Beauty', 'Inspection of Left Lower Leg, Perc Endo Approach', 213),
('Outdoors', 'Coord/Dexterity Trmt Neuro Up Back/UE w Prosthesis', 214),
('Beauty', 'Fusion of L Carpal Jt with Autol Sub, Perc Endo Approach', 215),
('Outdoors', 'Excision of Right Tympanic Membrane, Perc Approach, Diagn', 216),
('Tools', 'Repair Sternum, Percutaneous Approach', 217),
('Garden', 'Transfer Accessory Nerve to Acoustic Nerve, Open Approach', 218),
('Games', 'Drainage of Left Radius, Percutaneous Approach, Diagnostic', 219),
('Clothing', 'Reposition Right Ureter, Open Approach', 220),
('Grocery', 'Restrict R Renal Art w Extralum Dev, Perc Endo', 221),
('Tools', 'Dilate R Ext Carotid w 3 Intralum Dev, Perc Endo', 222),
('Grocery', 'Fluoroscopy of Cervical Spine using Other Contrast', 223),
('Health', 'Dilation of Right Basilic Vein, Open Approach', 224),
('Books', 'Compression of Right Upper Arm using Pressure Dressing', 225),
('Jewelry', 'Insertion of Radioact Elem into Periton Cav, Open Approach', 226),
('Books', 'Drainage of Esophagogastric Junction, Via Opening, Diagn', 227),
('Outdoors', 'Bypass R Com Iliac Art to B Ext Ilia w Autol Art, Open', 228),
('Electronics', 'Supplement Trigem Nrv with Autol Sub, Perc Endo Approach', 229),
('Sports', 'Drainage of Left Parotid Gland with Drain Dev, Open Approach', 230),
('Automotive', 'Removal of Synth Sub from R Clavicle, Perc Approach', 231),
('Garden', 'Extirpate of Matter from Perineum Tendon, Perc Endo Approach', 232),
('Sports', 'Resection of Int Mamm, L Lymph, Perc Endo Approach', 233),
('Automotive', 'Fusion of Right Knee Joint with Synth Sub, Perc Approach', 234),
('Industrial', 'Dilation of R Com Carotid with Intralum Dev, Perc Approach', 235),
('Computers', 'Replacement of Left Orbit with Autol Sub, Open Approach', 236),
('Outdoors', 'Fluoroscopy Cerv-cereb Arch w L Osm Contrast, Laser Intraop', 237),
('Tools', 'Supplement R Up Extrem Bursa/Lig w Autol Sub, Perc Endo', 238),
('Computers', 'Inspection of Left Foot, Percutaneous Endoscopic Approach', 239),
('Computers', 'Drainage of Left Elbow Region, Perc Endo Approach, Diagn', 240),
('Tools', 'Bypass Ascending Colon to Sigmoid Colon with Autol Sub, Endo', 241),
('Kids', 'Plain Radiography of Bi Salivary Gland using L Osm Contrast', 242),
('Clothing', 'Supplement Cervcal Vertebra w Nonaut Sub, Perc Endo', 243),
('Kids', 'Hyperthermia of Hypopharynx', 244),
('Garden', 'Destruction of Left Submaxillary Gland, Open Approach', 245),
('Industrial', 'Drainage of R Elbow Bursa/Lig with Drain Dev, Perc Approach', 246),
('Automotive', 'Bypass Ascending Colon to Asc Colon, Perc Endo Approach', 247),
('Sports', 'Release Left Upper Lung Lobe, Endo', 248),
('Shoes', 'Destruction of Right Thorax Muscle, Open Approach', 249),
('Electronics', 'Destruction of Olfactory Nerve, Open Approach', 250),
('Baby', 'Hyperthermia of Jejunum', 251),
('Health', 'Supplement Trachea with Nonaut Sub, Perc Endo Approach', 252),
('Music', 'Bypass Right Brachial Vein to Upper Vein, Open Approach', 253),
('Toys', 'Revision of Ext Fix in L Low Femur, Extern Approach', 254),
('Jewelry', 'Revision of Infusion Device in Penis, External Approach', 255),
('Beauty', 'Restriction of Esophagus, Via Natural or Artificial Opening', 256),
('Movies', 'Insertion of Infusion Device into Kidney, Endo', 257),
('Automotive', 'Excision of Trachea, Open Approach, Diagnostic', 258),
('Computers', 'Destruction of R Post Tib Art, Perc Endo Approach', 259),
('Music', 'Division of Left Humeral Shaft, Perc Endo Approach', 260),
('Toys', 'Remove of Infusion Dev from Tracheobronc Tree, Open Approach', 261),
('Electronics', 'Replacement of R Frontal Bone with Autol Sub, Perc Approach', 262),
('Shoes', 'Repair Left Innominate Vein, Percutaneous Approach', 263),
('Books', 'Fusion of Left Carpal Joint with Synth Sub, Perc Approach', 264),
('Automotive', 'Release Left Foot Vein, Open Approach', 265),
('Jewelry', 'Traction of Right Hand using Traction Apparatus', 266),
('Electronics', 'Dressing of Back using Bandage', 267),
('Home', 'Removal of Infusion Device from Face, Percutaneous Approach', 268),
('Music', 'Excision of Perineum Bursa/Lig, Perc Endo Approach, Diagn', 269),
('Beauty', 'Repair Left Ethmoid Sinus, Percutaneous Endoscopic Approach', 270),
('Home', 'Repair Left Sacroiliac Joint, External Approach', 271),
('Home', 'Dressing of Right Thumb using Bandage', 272),
('Computers', 'Fragmentation in Right Kidney Pelvis, Percutaneous Approach', 273),
('Games', 'Excision of Right Elbow Joint, Perc Endo Approach, Diagn', 274),
('Home', 'Reposition Left Acromioclavicular Joint, Perc Approach', 275),
('Books', 'Repair Left Pelvic Bone, Percutaneous Endoscopic Approach', 276),
('Tools', 'Removal of Autol Sub from C-thor Jt, Open Approach', 277),
('Shoes', 'Insertion of Infusion Device into Testis, Via Opening', 278),
('Jewelry', 'Drainage of Int Mamm, R Lymph with Drain Dev, Open Approach', 279),
('Books', 'Supplement R Foot Tendon with Synth Sub, Perc Endo Approach', 280),
('Garden', 'Removal of Synth Sub from Up Tendon, Open Approach', 281),
('Grocery', 'Bypass L Com Iliac Vein to Low Vein w Autol Vn, Perc Endo', 282),
('Baby', 'Dilate Intracran Art, Bifurc, w 3 Drug-elut, Perc', 283),
('Kids', 'Insertion of Intraluminal Device into Anus, Perc Approach', 284),
('Industrial', 'Reposition Left Toe Phalangeal Joint, Open Approach', 285),
('Industrial', 'Replacement of Left Breast with Synth Sub, Perc Approach', 286),
('Books', 'Reposition R Carpal Jt with Int Fix, Perc Endo Approach', 287),
('Kids', 'Destruction of Lumbar Spinal Cord, Percutaneous Approach', 288),
('Automotive', 'Insertion of Monitoring Device into Up Art, Open Approach', 289),
('Automotive', 'Dilate L Int Iliac Art, Bifurc, w 3 Drug-elut, Open', 290),
('Toys', 'Release Left Hip Tendon, External Approach', 291),
('Games', 'Supplement L Vas Deferens with Synth Sub, Perc Endo Approach', 292),
('Tools', 'Excision of Right Renal Vein, Perc Endo Approach, Diagn', 293),
('Tools', 'Drainage of Male Perineum, Percutaneous Approach, Diagnostic', 294),
('Automotive', 'Plain Radiography of Intracran Art using Oth Contrast', 295),
('Computers', 'Insert of Pedcl Stabl Dev into Cerv Jt, Perc Endo Approach', 296),
('Baby', 'Supplement R Finger Phalanx Jt with Autol Sub, Perc Approach', 297),
('Health', 'Dilation of L Subclav Vein with Intralum Dev, Open Approach', 298),
('Health', 'Dilation of Gastric Artery, Bifurcation, Perc Endo Approach', 299),
('Industrial', 'Excision of R Thorax Bursa/Lig, Perc Approach, Diagn', 300),
('Clothing', 'Dilation of L Fem Art using Drug Blln, Perc Approach', 301),
('Movies', 'Occlusion L Lg Intest w Extralum Dev, Perc Endo', 302),
('Home', 'High Dose Rate (HDR) Brachytherapy of Brain using Cesium 137', 303),
('Electronics', 'Dilation of Right Lower Lobe Bronchus, Via Opening', 304),
('Baby', 'Drainage of Right Ankle Joint, Percutaneous Approach', 305),
('Sports', 'Excision of Right Lacrimal Bone, Open Approach', 306),
('Grocery', 'Repair Abdomen Subcutaneous Tissue and Fascia, Perc Approach', 307),
('Kids', 'Removal of Autol Sub from L Humeral Shaft, Perc Approach', 308),
('Baby', 'Revision of Extraluminal Device in Lower Vein, Open Approach', 309),
('Health', 'Reposition Upper Vein, Percutaneous Approach', 310),
('Tools', 'Removal of Other Device on Face', 311),
('Toys', 'Replacement of Hyoid Bone with Autol Sub, Perc Endo Approach', 312),
('Outdoors', 'Excision of Left Sphenoid Sinus, Percutaneous Approach', 313),
('Movies', 'Bypass R Fem Art to L Femor A with Autol Vn, Open Approach', 314),
('Toys', 'Extirpate matter from R Shoulder Tendon, Perc Endo', 315),
('Kids', 'Drainage of Vagina, External Approach', 316),
('Jewelry', 'Bypass L Atrium to R Pulm Vn w Autol Art, Perc Endo', 317),
('Music', 'Insertion of Radioactive Element into R Wrist, Perc Approach', 318),
('Clothing', 'Revision of Nonaut Sub in Hepatobil Duct, Extern Approach', 319),
('Baby', 'Drainage of Urethra, Percutaneous Approach', 320),
('Clothing', 'Dilation of Hepatic Vein, Open Approach', 321),
('Grocery', 'HDR Brachytherapy of Larynx using Palladium 103', 322),
('Sports', 'Drainage of Left Common Iliac Vein, Percutaneous Approach', 323),
('Home', 'Drainage of Tongue, Percutaneous Approach', 324),
('Games', 'Restrict of R Axilla Lymph with Extralum Dev, Perc Approach', 325),
('Industrial', 'Drainage of L Up Lobe Bronc with Drain Dev, Via Opening', 326),
('Grocery', 'Excision of Pineal Body, Open Approach', 327),
('Games', 'Removal of Infusion Dev from Uterus & Cervix, Perc Approach', 328),
('Music', 'Cochlear Implant Assessment using Sound Field / Booth', 329),
('Grocery', 'Bypass L Com Iliac Art to L Com Ilia w Nonaut Sub, Open', 330),
('Movies', 'Repair Pelvis Lymphatic, Percutaneous Endoscopic Approach', 331),
('Kids', 'Traction of Left Lower Extremity using Traction Apparatus', 332),
('Baby', 'Fragmentation in Right Ureter, Percutaneous Approach', 333),
('Industrial', 'Revision of Synth Sub in L Toe Phalanx Jt, Perc Approach', 334),
('Tools', 'Extirpation of Matter from R Brach Vein, Perc Endo Approach', 335),
('Sports', 'Dilate 1 Cor Art w Radioact Intralum, Perc Endo', 336),
('Books', 'Reattachment of Transverse Colon, Open Approach', 337),
('Music', 'Remove Infusion Dev from L Temporomandib Jt, Perc Endo', 338),
('Movies', 'Drainage of Left Foot with Drainage Device, Open Approach', 339),
('Home', 'Release Right Anterior Tibial Artery, Perc Endo Approach', 340),
('Kids', 'Repair Cervical Vertebral Joint, Perc Endo Approach', 341),
('Sports', 'Fluoroscopy of Left Jugular Veins using Other Contrast', 342),
('Jewelry', 'Repair Left Upper Lung Lobe, Percutaneous Approach', 343),
('Electronics', 'Reposition Right Lung, Open Approach', 344),
('Tools', 'Repair Left Ethmoid Sinus, Percutaneous Endoscopic Approach', 345),
('Grocery', 'Dilation of R Fem Art with 3 Drug-elut, Perc Approach', 346),
('Outdoors', 'Replace Genitalia Skin w Autol Sub, Part Thick, Extern', 347),
('Music', 'Extirpation of Matter from Pulmonary Valve, Perc Approach', 348),
('Computers', 'Excision of Left External Iliac Artery, Open Approach', 349),
('Jewelry', 'Removal of Drainage Device from Bladder, External Approach', 350),
('Toys', 'Reposition Left Diaphragm, Open Approach', 351),
('Jewelry', 'Reposition Left Shoulder Joint, Percutaneous Approach', 352),
('Garden', 'Extirpation of Matter from Chordae Tendineae, Perc Approach', 353),
('Industrial', 'HDR Brachytherapy of Spleen using Californium 252', 354),
('Books', 'Occlusion R Verteb Art w Intralum Dev, Perc Endo', 355),
('Automotive', 'Excision of Ileocecal Valve, Via Opening', 356),
('Toys', 'Supplement L Shoulder Tendon with Synth Sub, Open Approach', 357),
('Computers', 'Restrict Ductus Arterio w Extralum Dev, Perc Endo', 358),
('Beauty', 'Supplement Left Clavicle with Synth Sub, Open Approach', 359),
('Kids', 'Resection of Perineum Muscle, Open Approach', 360),
('Electronics', 'Supplement Head with Nonaut Sub, Open Approach', 361),
('Toys', 'Control Bleeding in Right Shoulder Region, Open Approach', 362),
('Industrial', 'Destruction of Acoustic Nerve, Percutaneous Approach', 363),
('Sports', 'Removal of Autol Sub from Mouth/Throat, Endo', 364),
('Jewelry', 'Restriction of Stomach with Extralum Dev, Perc Approach', 365),
('Grocery', 'Repair Left 5th Toe, Percutaneous Endoscopic Approach', 366),
('Games', 'Removal of Synthetic Substitute from Brain, Open Approach', 367),
('Health', 'Reposition Left Common Iliac Vein, Perc Endo Approach', 368),
('Books', 'Excision of Thoracic Nerve, Perc Endo Approach, Diagn', 369),
('Kids', 'Repair Left Lower Lung Lobe, Perc Endo Approach', 370),
('Movies', 'Excision of Small Intestine, Via Opening', 371),
('Industrial', 'Restriction of R Hepatic Duct with Intralum Dev, Via Opening', 372),
('Books', 'Compression of Chest Wall using Intermittent Pressure Device', 373),
('Grocery', 'Insert Ext Fix in R Finger Phalanx Jt, Perc Endo', 374),
('Electronics', 'Supplement Bi Vas Deferens w Nonaut Sub, Perc Endo', 375),
('Electronics', 'Insertion of Int Fix into Thor Vertebra, Perc Endo Approach', 376),
('Clothing', 'Repair Hymen, Percutaneous Approach', 377),
('Shoes', 'Supplement Right Ureter with Autol Sub, Endo', 378),
('Games', 'Dilation of L Renal Art with Intralum Dev, Perc Approach', 379),
('Computers', 'Drainage of Thyroid Gland, Percutaneous Approach, Diagnostic', 380),
('Sports', 'Fluoroscopy of Cervical Spine using Other Contrast', 381),
('Grocery', 'Unitherm Biaur Screen Assess w Vestib/Balance Equip', 382),
('Industrial', 'Extirpation of Matter from Right Ankle Joint, Open Approach', 383),
('Outdoors', 'Resection of Urethra, Open Approach', 384),
('Music', 'Nuclear Medicine, MS Sys, Nonimag Nucl Med Prob', 385),
('Industrial', 'Nuclear Medicine, Urinary Sys, Nonimag Nucl Med Assay', 386),
('Shoes', 'Occlusion of Left Large Intestine, Open Approach', 387),
('Outdoors', 'Reposition Left Finger Phalanx with Int Fix, Open Approach', 388),
('Games', 'Reposition R Femur Shaft w Hybrid Ext Fix, Perc Endo', 389),
('Garden', 'Reposition Left Humeral Shaft, External Approach', 390),
('Shoes', 'Supplement R Little Finger w Autol Sub, Perc Endo', 391),
('Shoes', 'Replacement of L Up Eyelid with Synth Sub, Open Approach', 392),
('Grocery', 'Revision of Nonaut Sub in R Toe Phalanx Jt, Open Approach', 393),
('Toys', 'Bypass L Axilla Vein to Up Vein w Autol Sub, Open', 394),
('Jewelry', 'Reposition Anus, Endo', 395),
('Baby', 'Supplement Cystic Duct with Autol Sub, Perc Approach', 396),
('Automotive', 'Drainage of L Retinal Vessel with Drain Dev, Perc Approach', 397),
('Computers', 'Removal of Pressure Dressing on Right Upper Arm', 398),
('Games', 'Destruction of Gastric Artery, Percutaneous Approach', 399),
('Electronics', 'Reposition Descending Colon, Perc Endo Approach', 400),
('Shoes', 'HDR Brachytherapy of Bladder using Oth Isotope', 401),
('Shoes', 'Dilation of Anus with Intraluminal Device, Open Approach', 402),
('Electronics', 'Fluoroscopy of Right Renal Vein using High Osmolar Contrast', 403),
('Home', 'Revision of Infusion Device in Thymus, Open Approach', 404),
('Tools', 'Occlusion of Left Popliteal Artery, Open Approach', 405),
('Jewelry', 'Transfuse of Embr Stem Cell into Central Vein, Perc Approach', 406),
('Grocery', 'Removal of Drain Dev from L Pleural Cav, Perc Endo Approach', 407),
('Outdoors', 'Replacement of Celiac Artery with Nonaut Sub, Open Approach', 408),
('Garden', 'Repair Right Upper Leg, Percutaneous Approach', 409),
('Shoes', 'Repair Left Kidney Pelvis, Endo', 410),
('Garden', 'Drainage of Adenoids, Open Approach', 411),
('Home', 'Revise of Synth Sub in Up Extrem Subcu/Fascia, Open Approach', 412),
('Automotive', 'Release Coccygeal Glomus, Percutaneous Endoscopic Approach', 413),
('Home', 'Occlusion of Left Thyroid Artery, Open Approach', 414),
('Sports', 'Bypass R Com Iliac Art to R Ext Ilia w Autol Vn, Open', 415),
('Baby', 'Resection of R Ankle Bursa/Lig, Perc Endo Approach', 416),
('Home', 'Transfer L Abd Muscle with Skin, Subcu, Perc Endo Approach', 417),
('Grocery', 'Vocation/Commun Treatment', 418),
('Beauty', 'Removal of Autol Sub from L Acetabulum, Perc Endo Approach', 419),
('Games', 'Destruction of Right Metatarsal-Tarsal Joint, Perc Approach', 420),
('Kids', 'Bypass 2 Cor Art from L Int Mammary w Autol Vn, Open', 421),
('Clothing', 'Supplement Right Kidney Pelvis with Autol Sub, Endo', 422),
('Baby', 'Resection of Right Toe Phalangeal Joint, Open Approach', 423),
('Outdoors', 'Insertion of Infusion Dev into L Brach Vein, Perc Approach', 424),
('Health', 'Drainage of Spleen, Percutaneous Approach, Diagnostic', 425),
('Movies', 'Dilate of Trans Colon with Intralum Dev, Perc Endo Approach', 426),
('Garden', 'Removal of Nonaut Sub from L Carpal Jt, Open Approach', 427),
('Automotive', 'Revision of Int Fix in L Toe Phalanx Jt, Perc Endo Approach', 428),
('Jewelry', 'Bypass Right Axillary Artery to L Low Arm Art, Open Approach', 429),
('Electronics', 'Release Right Inguinal Lymphatic, Perc Endo Approach', 430),
('Games', 'Occlusion of Cystic Duct with Extralum Dev, Open Approach', 431),
('Clothing', 'Bypass Left Axillary Vein to Upper Vein, Perc Endo Approach', 432),
('Electronics', 'Remove Infusion Dev from Head & Neck Subcu/Fascia, Open', 433),
('Health', 'Drainage of Mesentery, Percutaneous Approach', 434),
('Movies', 'Revision of Infusion Device in Spleen, Percutaneous Approach', 435),
('Music', 'Dilate R Brach Art, Bifurc, w 4+ Intralum Dev, Perc Endo', 436),
('Garden', 'Head and Facial Bones, Inspection', 437),
('Toys', 'Repair Intracranial Vein, Percutaneous Approach', 438),
('Grocery', 'Extirpation of Matter from L Subclav Vein, Perc Approach', 439),
('Home', 'Release Pelvis Lymphatic, Percutaneous Endoscopic Approach', 440),
('Toys', 'Bypass L Ventricle to L Pulm Art w Synth Sub, Perc Endo', 441),
('Music', 'Replace of R Brach Vein with Synth Sub, Perc Endo Approach', 442),
('Home', 'Supplement L Up Extrem Bursa/Lig w Autol Sub, Perc Endo', 443),
('Home', 'Removal of Infusion Device from R Shoulder Jt, Open Approach', 444),
('Garden', 'Revision of Infusion Device in Penis, Perc Endo Approach', 445),
('Garden', 'Removal of Synthetic Substitute from Nose, Via Opening', 446),
('Garden', 'Occlusion of Right Subclavian Artery, Open Approach', 447),
('Movies', 'Restrict of Sup Mesent Vein with Intralum Dev, Perc Approach', 448),
('Shoes', 'Revision of Drain Dev in Pineal Body, Perc Endo Approach', 449),
('Books', 'Replace of R Knee Jt, Femoral with Synth Sub, Open Approach', 450),
('Health', 'Reposition R Wrist Jt with Int Fix, Perc Endo Approach', 451),
('Kids', 'Restrict L Ext Iliac Vein w Intralum Dev, Open', 452),
('Industrial', 'Replace of R Tympanic Membrane with Nonaut Sub, Via Opening', 453),
('Clothing', 'Replacement of Toe Nail with Nonaut Sub, Extern Approach', 454),
('Games', 'Immobilization of Left Lower Arm using Splint', 455),
('Home', 'Supplement Tricusp Valve fr R AV Vlv w Autol Sub, Open', 456),
('Toys', 'Create Penis in Fem Perineum w Synth Sub, Open', 457),
('Health', 'Introduction of Other Gas into Periton Cav, Via Opening', 458),
('Outdoors', 'Revision of Int Fix in L Femur Shaft, Perc Approach', 459),
('Electronics', 'Destruction of L Ext Auditory Canal, Perc Endo Approach', 460),
('Electronics', 'Removal of Nonaut Sub from Omentum, Open Approach', 461),
('Computers', 'Restriction of Mesenteric Lymphatic, Percutaneous Approach', 462),
('Music', 'Excision of Left Conjunctiva, External Approach', 463),
('Home', 'Revise Infusion Pump in Up Extrem Subcu/Fascia, Extern', 464),
('Automotive', 'Occlusion of Left Brachial Vein, Perc Endo Approach', 465),
('Sports', 'Removal of Ext Fix from R Humeral Shaft, Perc Approach', 466),
('Shoes', 'Remove Infusion Dev from Head & Neck Subcu/Fascia, Extern', 467),
('Health', 'Transplantation of Small Intestine, Zooplast, Open Approach', 468),
('Music', 'Drainage of Right External Jugular Vein, Open Approach', 469),
('Kids', 'CT Scan of Bi Renal Vein using L Osm Contrast', 470),
('Shoes', 'Removal of Radioact Elem from R Up Extrem, Extern Approach', 471),
('Tools', 'Repair Right Upper Leg, Open Approach', 472),
('Tools', 'Revision of Extralum Dev in Low Vein, Perc Endo Approach', 473),
('Jewelry', 'Dilation of Right Common Carotid Artery, Perc Endo Approach', 474),
('Music', 'Revision of Infusion Dev in R Elbow Jt, Perc Endo Approach', 475),
('Grocery', 'Dilate R Int Mamm Art, Bifurc, w 4 Drug-elut, Open', 476),
('Baby', 'Plain Radiography of Left Epididymis using H Osm Contrast', 477),
('Garden', 'Reposition R Humeral Head with Hybrid Ext Fix, Perc Approach', 478),
('Shoes', 'Insertion of Intramed Fix into R Ulna, Perc Endo Approach', 479),
('Beauty', 'Bypass Com Bile Duct to R Hep Duc w Intralum Dev, Open', 480),
('Movies', 'Planar Nucl Med Imag Head & Neck Lymph w Oth Radionuclide', 481),
('Electronics', 'Release Lower Tooth, Single, Open Approach', 482),
('Music', 'Drainage of Left Lower Lung Lobe with Drain Dev, Via Opening', 483),
('Games', 'Destruction of Left Lower Eyelid, Percutaneous Approach', 484),
('Automotive', 'Division of L Shoulder Bursa/Lig, Perc Endo Approach', 485),
('Computers', 'Supplement Left Hand Artery with Nonaut Sub, Perc Approach', 486),
('Games', 'CT Scan of L Ankle using H Osm Contrast', 487),
('Kids', 'Restriction of Stomach, Via Natural or Artificial Opening', 488),
('Clothing', 'Drainage of Left Palatine Bone, Open Approach, Diagnostic', 489),
('Industrial', 'Drainage of Right Breast, Via Natural or Artificial Opening', 490),
('Grocery', 'Lower Joints, Revision', 491),
('Games', 'Release Right Vocal Cord, Open Approach', 492),
('Grocery', 'Replacement of Pancreatic Duct with Synth Sub, Open Approach', 493),
('Books', 'Supplement R Up Leg Tendon w Synth Sub, Perc Endo', 494),
('Computers', 'Release Lower Tooth, All, Open Approach', 495),
('Outdoors', 'Revision of Nonaut Sub in Cerv Disc, Open Approach', 496),
('Beauty', 'Excision of Left Lacrimal Bone, Open Approach', 497),
('Beauty', 'Insertion of Tissue Expander into Right Breast, Via Opening', 498),
('Baby', 'Fusion of R Sternoclav Jt with Synth Sub, Perc Endo Approach', 499),
('Home', 'Home Management Treatment using Other Equipment', 500),
('Automotive', 'Repair GI Sys in POC with Oth Dev, Via Opening', 501),
('Automotive', 'Revision of Monitor Dev in Spinal Cord, Extern Approach', 502),
('Clothing', 'Bypass Right Kidney Pelvis to Ileocutan, Perc Endo Approach', 503),
('Automotive', 'Revision of Infusion Device in R Knee Jt, Open Approach', 504),
('Books', 'Occlusion Azygos Vein w Intralum Dev, Perc Endo', 505),
('Beauty', 'CT Scan of R Humerus using L Osm Contrast', 506),
('Shoes', 'Bypass L Ext Iliac Art to Low Ex Art w Autol Art, Perc Endo', 507),
('Outdoors', 'Drainage of R Glenoid Cav with Drain Dev, Perc Approach', 508),
('Outdoors', 'Revision of Autol Sub in Finger Nail, Extern Approach', 509),
('Jewelry', 'Replace of R Temporomandib Jt with Nonaut Sub, Open Approach', 510),
('Books', 'MRI of L Kidney using Oth Contrast', 511),
('Industrial', 'Drainage of Spleen, Open Approach, Diagnostic', 512),
('Books', 'Revision of Synth Sub in R Humeral Head, Perc Approach', 513),
('Books', 'Dilate L Ext Iliac Art w 2 Intralum Dev, Perc Endo', 514),
('Grocery', 'Revision of Autol Sub in Nose, Perc Approach', 515),
('Sports', 'Revise of Nonaut Sub in Prostate/Seminal Ves, Open Approach', 516),
('Home', 'Dilate 2 Cor Art, Bifurc, w Intralum Dev, Perc', 517),
('Games', 'Replace Face Skin w Synth Sub, Part Thick, Extern', 518),
('Books', 'Alteration of Nose, External Approach', 519),
('Beauty', 'Drainage of Penis with Drainage Device, Perc Approach', 520),
('Games', 'Removal of Tracheostomy Device from Trachea, Extern Approach', 521),
('Automotive', 'Release Uterine Supporting Structure, Open Approach', 522),
('Outdoors', 'Extirpation of Matter from R Inqnl Lymph, Open Approach', 523),
('Beauty', 'Removal of Autol Sub from R Humeral Shaft, Open Approach', 524),
('Kids', 'Bypass 1 Cor Art from Cor Art w Synth Sub, Perc Endo', 525),
('Music', 'Supplement Right 5th Toe with Synth Sub, Perc Endo Approach', 526),
('Automotive', 'Replacement of Left Eye with Synth Sub, Perc Approach', 527),
('Industrial', 'Eye, Fragmentation', 528),
('Beauty', 'Fusion Cerv Jt w Autol Sub, Post Appr P Col, Perc Endo', 529),
('Beauty', 'Restriction of Right Axillary Artery, Open Approach', 530),
('Shoes', 'Computerized Tomography (CT Scan) of Superior Vena Cava', 531),
('Clothing', 'Removal of Traction Apparatus on Right Upper Extremity', 532),
('Shoes', 'Bypass Ascending Colon to Asc Colon, Perc Endo Approach', 533),
('Books', 'Replace of L Glenoid Cav with Synth Sub, Perc Endo Approach', 534),
('Sports', 'Removal of Intralum Dev from Mouth/Throat, Open Approach', 535),
('Industrial', 'Fluoroscopy of Superior Vena Cava using Low Osmolar Contrast', 536),
('Garden', 'Excision of Right Testis, Percutaneous Endoscopic Approach', 537),
('Clothing', 'Remove Implant Heart Assist from Heart, Perc Endo', 538),
('Electronics', 'Bypass 4+ Cor Art from L Int Mammary w Synth Sub, Perc Endo', 539),
('Music', 'Supplement R Hypogast Vein with Synth Sub, Perc Approach', 540),
('Shoes', 'Insertion of Artificial Sphincter into Urethra, Via Opening', 541),
('Garden', 'Insert Limb Length Dev in R Up Femur, Perc Endo', 542),
('Grocery', 'Ultrasonography of Inferior Vena Cava', 543),
('Books', 'Release Right Neck Muscle, Percutaneous Endoscopic Approach', 544),
('Clothing', 'Transfer L Hip Muscle with Skin, Subcu, Perc Endo Approach', 545),
('Electronics', 'Extraction of R Low Leg Subcu/Fascia, Perc Approach', 546),
('Sports', 'Destruction of Right Ethmoid Sinus, Percutaneous Approach', 547),
('Shoes', 'Introduce Electrol/Water Bal in Periph Vein, Open', 548),
('Home', 'Repair Left Pulmonary Artery, Perc Endo Approach', 549),
('Jewelry', 'Division of R Thorax Bursa/Lig, Perc Endo Approach', 550),
('Industrial', 'Extirpation of Matter from Bi Adrenal Gland, Perc Approach', 551),
('Music', 'Revision of Int Fix in L Metacarpal, Perc Approach', 552),
('Music', 'Resection of Bilateral Seminal Vesicles, Perc Endo Approach', 553),
('Jewelry', 'Supplement R Acromioclav Jt with Synth Sub, Open Approach', 554),
('Kids', 'Division of Right Foot Muscle, Perc Endo Approach', 555),
('Books', 'Release Thymus, Percutaneous Endoscopic Approach', 556),
('Industrial', 'Revision of Synth Sub in L Knee Jt, Perc Endo Approach', 557),
('Industrial', 'LDR Brachytherapy of Thymus using Palladium 103', 558),
('Jewelry', 'Supplement L Up Leg Tendon w Autol Sub, Perc Endo', 559),
('Toys', 'Extirpate of Matter from L Hand Subcu/Fascia, Open Approach', 560),
('Toys', 'Bypass R Kidney Pelvis to Colon w Nonaut Sub, Open', 561),
('Games', 'Introduction of Oth Anti-infect into Mouth/Phar, Via Opening', 562),
('Home', 'Excision of Back Subcu/Fascia, Perc Approach', 563),
('Automotive', 'Release Right Parietal Bone, Perc Endo Approach', 564),
('Books', 'Release Bilateral Carotid Bodies, Perc Endo Approach', 565),
('Kids', 'Supplement L Metatarsophal Jt with Synth Sub, Perc Approach', 566),
('Automotive', 'Inspection of Bilateral Inguinal Region, Perc Approach', 567),
('Sports', 'Osteopathic Treatment of Lower Extremities using Lymph Pump', 568),
('Clothing', 'Excision of Right Upper Lung Lobe, Open Approach, Diagnostic', 569),
('Music', 'Revision of Autologous Tissue Substitute in Penis, Endo', 570),
('Shoes', 'Destruction of Left Palatine Bone, Percutaneous Approach', 571),
('Kids', 'Removal of Autol Sub from R Wrist Jt, Perc Approach', 572),
('Computers', 'Alteration of Right Lower Arm with Autol Sub, Perc Approach', 573),
('Movies', 'Destruction of R Sup Parathyroid, Perc Approach', 574),
('Clothing', 'Fluoroscopy of L Temporomand Jt using H Osm Contrast', 575),
('Garden', 'Low Dose Rate (LDR) Brachytherapy of Pleura using Cesium 137', 576),
('Electronics', 'Drainage of L Foot Muscle with Drain Dev, Perc Endo Approach', 577),
('Sports', 'Supplement R Humeral Shaft w Nonaut Sub, Perc Endo', 578),
('Outdoors', 'Drainage of Jejunum with Drainage Device, Perc Approach', 579),
('Shoes', 'Fusion of L Toe Phalanx Jt with Ext Fix, Perc Approach', 580),
('Tools', 'Anatomical Regions, Lower Extremities, Change', 581),
('Industrial', 'Osteopathic Treatment of Rib Cage using Other Method', 582),
('Beauty', 'Reposition Left Metatarsal-Tarsal Joint, Perc Approach', 583),
('Home', 'Supplement Right Patella with Autol Sub, Perc Endo Approach', 584),
('Tools', 'Removal of Other Device from GI Tract, Open Approach', 585),
('Baby', 'Dilate Sup Mesent Art, Bifurc, w 2 Drug-elut, Open', 586),
('Automotive', 'Drainage of Coccygeal Joint, Percutaneous Approach, Diagn', 587),
('Home', 'Revision of Drainage Device in Left Hip Joint, Perc Approach', 588),
('Toys', 'Excision of Cystic Duct, Percutaneous Endoscopic Approach', 589),
('Sports', 'Repair Thorax Lymphatic, Percutaneous Approach', 590),
('Jewelry', 'Bypass L Fem Art to Foot Art with Autol Art, Open Approach', 591),
('Health', 'Dilate L Peroneal Art, Bifurc, w 3 Drug-elut, Open', 592),
('Garden', 'Bypass L Int Iliac Art to B Int Ilia w Nonaut Sub, Perc Endo', 593),
('Jewelry', 'Destruction of Left Ulna, Percutaneous Endoscopic Approach', 594),
('Music', 'Alteration of Right External Ear, Open Approach', 595),
('Shoes', 'Destruction of Right Metatarsal, Open Approach', 596),
('Music', 'Change Bandage on Right Lower Extremity', 597),
('Garden', 'Repair Thoracic Vertebral Disc, Perc Endo Approach', 598),
('Health', 'Beam Radiation of Pelvic Bones using Neutrons', 599),
('Movies', 'Reposition Left Shoulder Joint with Int Fix, Perc Approach', 600),
('Jewelry', 'Revision of Synth Sub in Ureter, Perc Endo Approach', 601),
('Health', 'Fluoroscopy of Bi Com Carotid using L Osm Contrast', 602),
('Industrial', 'Bypass 1 Cor Art from Aorta w Nonaut Sub, Perc Endo', 603),
('Books', 'Restriction of Right Hepatic Duct, Perc Endo Approach', 604),
('Jewelry', 'Replacement of Sternum with Autol Sub, Perc Approach', 605),
('Sports', 'Replace L Hip Jt w Ceramic on Poly, Cement, Open', 606),
('Jewelry', 'Inspection of Kidney, External Approach', 607),
('Sports', 'Destruction of Left Breast, Percutaneous Approach', 608),
('Health', 'Control Bleeding in Right Axilla, Open Approach', 609),
('Electronics', 'Fusion of Right Knee Joint with Synth Sub, Open Approach', 610),
('Garden', 'Replacement of Left Nipple with Synth Sub, Perc Approach', 611),
('Jewelry', 'Inspection of Left Carpal Joint, Open Approach', 612),
('Shoes', 'Central Nervous System, Excision', 613),
('Books', 'Dilation of Descend Colon with Intralum Dev, Perc Approach', 614),
('Books', 'CT Scan of L Up Extrem using L Osm Contrast', 615),
('Computers', 'Introduce Serum/Tox/Vaccine in Central Art, Perc', 616),
('Books', 'Extirpate matter from R Temporal Art, Bifurc, Open', 617),
('Baby', 'Excision of Right Atrium, Percutaneous Approach, Diagnostic', 618),
('Beauty', 'Excision of R Knee Bursa/Lig, Perc Endo Approach', 619),
('Grocery', 'Revision of Drainage Device in R Knee Jt, Open Approach', 620),
('Grocery', 'Bypass Upper Esophagus to Ileum, Open Approach', 621),
('Health', 'Female Reproductive System, Dilation', 622),
('Home', 'Supplement Left Elbow Joint with Autol Sub, Open Approach', 623),
('Music', 'Destruction of Left Vertebral Vein, Percutaneous Approach', 624),
('Movies', 'Excision of Right Hip Bursa and Ligament, Open Approach', 625),
('Grocery', 'Removal of Drainage Device from Facial Bone, Perc Approach', 626),
('Automotive', 'Insert Tissue Expander in L Hand Subcu/Fascia, Open', 627),
('Baby', 'LDR Brachytherapy of Ileum using Palladium 103', 628),
('Grocery', 'Dilation of R Renal Art with 4 Drug-elut, Perc Approach', 629),
('Home', 'Lower Arteries, Excision', 630),
('Tools', 'Transfer R Up Extrem Bursa/Lig, Open Approach', 631),
('Games', 'Insertion of Monitor Dev into L Atrium, Perc Endo Approach', 632),
('Outdoors', 'Plain Radiography of Right Hip using Other Contrast', 633),
('Garden', 'Destruction of Right Occipital Bone, Percutaneous Approach', 634),
('Electronics', 'Release Left Lacrimal Duct, Via Opening', 635),
('Sports', 'Planar Nucl Med Imag of Low Extrem using Iodine 131', 636),
('Garden', 'Supplement Left Tarsal Joint with Nonaut Sub, Perc Approach', 637),
('Home', 'Bypass Bi Ureter to Ileum with Autol Sub, Open Approach', 638),
('Books', 'Drainage of Left Ankle Joint, Open Approach', 639),
('Toys', 'Division of Left Hand Bursa and Ligament, Perc Approach', 640),
('Toys', 'Revision of Neurostimulator Lead in Brain, Perc Approach', 641),
('Games', 'Plain Radiography of Left Ankle using High Osmolar Contrast', 642),
('Movies', 'Insert Singl Array Rchg Stim Gen in Abd Subcu/Fascia, Open', 643),
('Grocery', 'Supplement Epiglottis with Synth Sub, Open Approach', 644),
('Sports', 'Excision of L Up Leg Subcu/Fascia, Open Approach', 645),
('Baby', 'Dilate R Axilla Art, Bifurc, w Drug-elut Intra, Perc', 646),
('Home', 'Reposition Right Vocal Cord, Open Approach', 647),
('Jewelry', 'Excision of Right Carpal, Percutaneous Endoscopic Approach', 648),
('Games', 'Dilate L Post Tib Art, Bifurc, w 4 Drug-elut, Open', 649),
('Games', 'Dilation of Rectum with Intraluminal Device, Endo', 650),
('Electronics', 'Alteration of Right Upper Leg with Nonaut Sub, Perc Approach', 651),
('Movies', 'Drainage of R Wrist Bursa/Lig with Drain Dev, Open Approach', 652),
('Sports', 'Removal of Synth Sub from Periton Cav, Perc Approach', 653),
('Toys', 'Fusion Occip Jt w Synth Sub, Post Appr P Col, Open', 654),
('Outdoors', 'Revision of Infusion Device in Thor Disc, Extern Approach', 655),
('Sports', 'Bypass Thor Aorta Asc to Carotid, Perc Endo Approach', 656),
('Tools', 'Replace R Low Leg Skin w Autol Sub, Part Thick, Extern', 657),
('Outdoors', 'Bypass 3 Cor Art from R Int Mammary w Autol Art, Open', 658),
('Clothing', 'Reposition Left Humeral Shaft with Int Fix, Perc Approach', 659),
('Baby', 'Destruction of Left Vocal Cord, Via Opening', 660),
('Music', 'Replacement of L Low Femur with Nonaut Sub, Open Approach', 661),
('Grocery', 'Supplement Left Inner Ear with Autol Sub, Open Approach', 662),
('Grocery', 'Extirpation of Matter from Right Ureter, Perc Approach', 663),
('Industrial', 'Drainage of Right Femoral Vein, Perc Endo Approach', 664),
('Grocery', 'Removal of Spacer from R Metacarpocarp Jt, Perc Approach', 665),
('Baby', 'Insert Infusion Dev in R Metacarpophal Jt, Perc', 666),
('Computers', 'Removal of Nonaut Sub from L Ankle Jt, Perc Endo Approach', 667),
('Sports', 'Drainage of Buccal Mucosa, Open Approach', 668),
('Outdoors', 'Release Right Renal Vein, Percutaneous Endoscopic Approach', 669),
('Garden', 'Replace L Up Leg Subcu/Fascia w Synth Sub, Perc', 670),
('Baby', 'Insertion of Monopln Ext Fix into R Low Femur, Perc Approach', 671),
('Electronics', 'Change Other Device on Left Foot', 672),
('Grocery', 'Drainage of Stomach, Pylorus, Endo', 673),
('Grocery', 'Dilate L Int Iliac Art, Bifurc, w Intralum Dev, Perc', 674),
('Clothing', 'Repair Left Buttock, Percutaneous Approach', 675),
('Sports', 'Revision of Intralum Dev in Up Intest Tract, Perc Approach', 676),
('Electronics', 'Removal of Nonaut Sub from Lum Vertebra, Perc Approach', 677),
('Tools', 'Bypass Splenic Vein to R Renal Vein w Autol Vn, Open', 678),
('Jewelry', 'Beam Radiation of Spleen using Heavy Particles', 679),
('Tools', 'Insertion of Ring Ext Fix into L Ulna, Perc Endo Approach', 680),
('Outdoors', 'Dilate R Thyroid Art w Drug-elut Intra, Perc Endo', 681),
('Music', 'Radiation Therapy, Fem Reprod Sys, Stereo Radiosurg', 682),
('Health', 'Occlusion of R Int Carotid, Perc Endo Approach', 683),
('Electronics', 'Drainage of Right External Auditory Canal, Via Opening', 684),
('Music', 'LDR Brachytherapy of Parathyroid Glands using Oth Isotope', 685),
('Home', 'Removal of Pressure Dressing on Abdominal Wall', 686),
('Computers', 'Excision of Colic Vein, Percutaneous Approach, Diagnostic', 687),
('Music', 'Supplement Lum Disc with Synth Sub, Open Approach', 688),
('Automotive', 'Revision of Nonaut Sub in T-lum Jt, Extern Approach', 689),
('Shoes', 'Destruction of Left Large Intestine, Percutaneous Approach', 690),
('Health', 'Excision of Lower Jaw, Open Approach', 691),
('Shoes', 'Fusion of Right Ankle Joint with Nonaut Sub, Open Approach', 692),
('Baby', 'Supplement Lower Vein with Nonaut Sub, Perc Approach', 693),
('Industrial', 'Dilation of Duodenum with Intraluminal Device, Open Approach', 694),
('Tools', 'Dilation of 3 Cor Art, Bifurc, Perc Approach', 695),
('Tools', 'Replacement of R Atrium with Nonaut Sub, Perc Endo Approach', 696),
('Books', 'Drain of R Com Iliac Vein with Drain Dev, Perc Endo Approach', 697),
('Jewelry', 'Release Lumbosacral Plexus, Percutaneous Endoscopic Approach', 698),
('Sports', 'Removal of Ext Fix from R Tarsal Jt, Perc Endo Approach', 699),
('Movies', 'Destruction of Peritoneum, Percutaneous Approach', 700),
('Games', 'Repair Esophageal Vein, Percutaneous Approach', 701),
('Sports', 'Planar Nucl Med Imag of Abd using Oth Radionuclide', 702),
('Electronics', 'Reposition Right Mandible with Ext Fix, Perc Approach', 703),
('Tools', 'Replacement of Left Hip Joint with Synth Sub, Open Approach', 704),
('Movies', 'Excision of Right Abdomen Tendon, Open Approach', 705),
('Beauty', 'Repair Stomach, Open Approach', 706),
('Tools', 'Drainage of R Carpal Jt with Drain Dev, Perc Endo Approach', 707),
('Grocery', 'Revision of Int Fix in R Femur Shaft, Open Approach', 708),
('Outdoors', 'Supplement R Ant Tib Art with Nonaut Sub, Perc Approach', 709),
('Jewelry', 'Reposition Left Metacarpophalangeal Joint, External Approach', 710),
('Grocery', 'MRI of R Low Leg using Oth Contrast', 711),
('Jewelry', 'Dilation of R Axilla Art with 4+ Intralum Dev, Perc Approach', 712),
('Computers', 'Removal of Radioactive Element from Omentum, Open Approach', 713),
('Baby', 'Bypass Jejunum to Rectum with Nonaut Sub, Endo', 714),
('Music', 'Drainage of L Ankle Jt with Drain Dev, Perc Endo Approach', 715),
('Tools', 'Fusion 2-6 C Jt w Nonaut Sub, Post Appr P Col, Open', 716),
('Garden', 'Bypass Bi Ureter to Ileum with Synth Sub, Perc Endo Approach', 717),
('Sports', 'Drainage of Left Hypogastric Vein, Percutaneous Approach', 718),
('Clothing', 'Dilation of L Popl Art with 3 Drug-elut, Perc Endo Approach', 719),
('Garden', 'Insertion of Pressure Sens into L Pulm Art, Open Approach', 720),
('Electronics', 'Release Left Vertebral Vein, Open Approach', 721),
('Clothing', 'Dilate L Colic Art, Bifurc, w 4 Drug-elut, Open', 722),
('Computers', 'Drain of Hemiazygos Vein with Drain Dev, Perc Endo Approach', 723),
('Computers', 'Repair Left Femoral Region, Percutaneous Endoscopic Approach', 724),
('Automotive', 'Extirpation of Matter from Right Trunk Tendon, Open Approach', 725),
('Shoes', 'Transfuse of Nonaut Globulin into Central Art, Perc Approach', 726),
('Computers', 'Revision of Autol Sub in Nasal Bone, Extern Approach', 727),
('Toys', 'Occlusion R Subclav Vein w Extralum Dev, Perc Endo', 728),
('Jewelry', 'Bypass Innom Art to R Extracran Art w Synth Sub, Open', 729),
('Books', 'Dilate R Verteb Art, Bifurc, w Drug-elut Intra, Perc', 730),
('Toys', 'Revision of Stimulator Lead in Bladder, Perc Approach', 731),
('Toys', 'Supplement R Seminal Vesicle with Synth Sub, Open Approach', 732),
('Computers', 'Restrict of R Foot Art with Intralum Dev, Perc Endo Approach', 733),
('Industrial', 'Revision of Monitoring Device in Ureter, Via Opening', 734),
('Electronics', 'Release Right Ear Skin, External Approach', 735),
('Home', 'Fusion 2-7 T Jt w Nonaut Sub, Ant Appr A Col, Perc', 736),
('Games', 'Occlusion L Axilla Vein w Intralum Dev, Perc Endo', 737),
('Grocery', 'Dilation of Upper Vein with Intralum Dev, Perc Approach', 738),
('Industrial', 'Insert of Infusion Dev into L Pulm Art, Perc Endo Approach', 739),
('Grocery', 'Supplement Bi Femoral Region with Nonaut Sub, Open Approach', 740),
('Grocery', 'Computerized Tomography (CT Scan) of Right Shoulder', 741),
('Automotive', 'Revision of Intralum Dev in Fallopian Tube, Perc Approach', 742),
('Movies', 'Repair Left Hand Artery, Percutaneous Approach', 743),
('Music', 'Destruction of Right Lacrimal Bone, Open Approach', 744),
('Sports', 'Supplement Left Orbit with Nonaut Sub, Perc Endo Approach', 745),
('Outdoors', 'Revision of Ext Fix in L Low Femur, Open Approach', 746),
('Kids', 'Reposition R Abd Bursa/Lig, Perc Endo Approach', 747),
('Clothing', 'Repair Left Pulmonary Artery, Perc Endo Approach', 748),
('Tools', 'Revision of Autol Sub in L Low Extrem, Perc Endo Approach', 749),
('Baby', 'Exercise Treatment of Resp Body using Aerobic Equipment', 750),
('Clothing', 'Drainage of R Acromioclav Jt, Open Approach, Diagn', 751),
('Shoes', 'LDR Brachytherapy of Urethra using Oth Isotope', 752),
('Books', 'Extirpation of Matter from Right Acetabulum, Perc Approach', 753),
('Electronics', 'Supplement Vagina with Autologous Tissue Substitute, Endo', 754),
('Electronics', 'Drainage of Right Lower Arm with Drain Dev, Perc Approach', 755),
('Sports', 'Control Bleeding in Right Ankle Region, Perc Approach', 756),
('Tools', 'Release Thoracic Vertebra, Percutaneous Endoscopic Approach', 757),
('Kids', 'Excision of Perineum Tendon, Open Approach, Diagnostic', 758),
('Shoes', 'Occlusion R Com Iliac Art w Intralum Dev, Open', 759),
('Kids', 'Replacement of Left Tympanic Membrane with Synth Sub, Endo', 760),
('Shoes', 'Removal of Diaphragm Lead from Diaphragm, Open Approach', 761),
('Tools', 'Fluoroscopy Bi Int Carotid w L Osm Contrast, Laser Intraop', 762),
('Home', 'Fusion of R Sternoclav Jt with Nonaut Sub, Perc Approach', 763),
('Jewelry', 'Extirpation of Matter from Left Ankle Joint, Perc Approach', 764),
('Industrial', 'Inspection of Right Breast, Via Opening', 765),
('Baby', 'Occlusion of Left Vertebral Vein, Perc Endo Approach', 766),
('Computers', 'MRI of L Eye using Oth Contrast, Unenh, Enhance', 767),
('Outdoors', 'Bypass Abd Aorta to L Int Ilia w Autol Art, Perc Endo', 768),
('Baby', 'Bypass Azygos Vein to Up Vein with Nonaut Sub, Open Approach', 769),
('Movies', 'Revision of Radioactive Element in Neck, Perc Approach', 770),
('Automotive', 'Revision of Spacer in Left Sacroiliac Joint, Extern Approach', 771),
('Beauty', 'Insert Endobronch Valve in R Low Lobe Bronc, Perc', 772),
('Grocery', 'Removal of Autol Sub from R Wrist Jt, Perc Endo Approach', 773),
('Kids', 'Removal of Ext Fix from L Ulna, Open Approach', 774),
('Grocery', 'Dilate L Int Iliac Art, Bifurc, w 2 Intralum Dev, Perc Endo', 775),
('Kids', 'Transfer Head Muscle, Percutaneous Endoscopic Approach', 776),
('Clothing', 'Remove of Autol Sub from Prostate/Seminal Ves, Open Approach', 777),
('Toys', 'Excision of L Finger Phalanx Jt, Open Approach, Diagn', 778),
('Beauty', 'Insertion of Radioact Elem into L Elbow, Perc Endo Approach', 779),
('Sports', 'Revision of Autol Sub in L Fibula, Extern Approach', 780),
('Garden', 'Obstetrics, Pregnancy, Change', 781),
('Beauty', 'Revision of Synth Sub in R Acromioclav Jt, Open Approach', 782),
('Health', 'Dilation of L Int Carotid with 3 Drug-elut, Open Approach', 783),
('Sports', 'Drainage of Optic Nerve, Percutaneous Approach', 784),
('Baby', 'Restriction of Common Bile Duct, Via Opening', 785),
('Movies', 'Revision of Infusion Device in R Ankle Jt, Open Approach', 786),
('Automotive', 'Release Urethra, Percutaneous Approach', 787),
('Tools', 'Ultrasonography of Right Heart using Other Contrast', 788),
('Jewelry', 'Fragmentation in Descending Colon, Perc Endo Approach', 789),
('Automotive', 'Excision of Left Greater Saphenous Vein, Perc Endo Approach', 790),
('Health', 'Bypass R Com Iliac Art to Mesent Art w Synth Sub, Open', 791),
('Home', 'Revision of Autol Sub in Low Vein, Perc Approach', 792),
('Toys', 'Revision of Drainage Device in Brain, Perc Endo Approach', 793),
('Automotive', 'Muscle Perform Assess Integu Up Back/UE w Prosthesis', 794),
('Baby', 'Change Intermittent Pressure Device on Left Foot', 795),
('Computers', 'Coordination/Dexterity Treatment of Integu Up Back/UE', 796),
('Industrial', 'Repair Right Vitreous, Percutaneous Approach', 797),
('Electronics', 'Removal of Drainage Device from Low Jaw, Perc Endo Approach', 798),
('Baby', 'Supplement R Fem Art with Synth Sub, Perc Endo Approach', 799),
('Grocery', 'Removal of Intraluminal Device from Larynx, Via Opening', 800),
('Shoes', 'Supplement Lum Jt with Synth Sub, Perc Approach', 801),
('Books', 'Planar Nucl Med Imag of Chest & Abd using Thallium 201', 802),
('Kids', 'Removal of Cast on Neck', 803),
('Kids', 'Release R Up Extrem Bursa/Lig, Open Approach', 804),
('Outdoors', 'Fusion of Left Wrist Joint with Ext Fix, Open Approach', 805),
('Automotive', 'Division of Left Frontal Bone, Perc Endo Approach', 806),
('Baby', 'Revision of Nonaut Sub in Kidney, Via Opening', 807),
('Industrial', 'Insertion of Other Device into R Axilla, Perc Endo Approach', 808),
('Music', 'Supplement R Int Mamm Art with Nonaut Sub, Perc Approach', 809),
('Beauty', 'Removal of Int Fix from L Clavicle, Extern Approach', 810),
('Shoes', 'Repair Right Upper Leg, Percutaneous Approach', 811),
('Books', 'Drainage of Duodenum with Drainage Device, Endo', 812),
('Movies', 'Dilate of L Int Carotid with 4+ Intralum Dev, Open Approach', 813),
('Garden', 'Removal of Drain Dev from R Metacarpophal Jt, Open Approach', 814),
('Baby', 'Dilation of L Post Tib Art with 2 Drug-elut, Perc Approach', 815),
('Shoes', 'Drainage of Subdural Space, Percutaneous Approach, Diagn', 816),
('Beauty', 'Restriction of Intracranial Artery, Percutaneous Approach', 817),
('Kids', 'Occlusion of L Post Tib Art with Extralum Dev, Open Approach', 818),
('Garden', 'Restrict of R Basilic Vein with Extralum Dev, Open Approach', 819),
('Clothing', 'Drainage of Left Large Intestine, Via Opening', 820),
('Games', 'Excision of Hard Palate, Open Approach', 821),
('Shoes', 'Fragmentation in Uterus, Open Approach', 822),
('Kids', 'Replacement of L Radius with Nonaut Sub, Perc Endo Approach', 823),
('Baby', 'Restriction of Right Hand Artery, Open Approach', 824),
('Games', 'Drainage of Thymus, Percutaneous Approach', 825),
('Shoes', 'Drainage of Pineal Body, Open Approach, Diagnostic', 826),
('Automotive', 'Remove Extralum Dev from Epididymis/Sperm Cord, Perc', 827),
('Industrial', 'Restriction of Mid Esophag with Intralum Dev, Via Opening', 828),
('Kids', 'Reposition Left Carpal with Int Fix, Open Approach', 829),
('Clothing', 'Inspection of Left Knee Region, Percutaneous Approach', 830),
('Home', 'Repair Left Acromioclavicular Joint, Open Approach', 831),
('Health', 'Revision of Radioactive Element in Neck, Open Approach', 832),
('Industrial', 'Reposition Thor Jt with Int Fix, Open Approach', 833),
('Grocery', 'Restrict Mid Colic Art w Intralum Dev, Perc Endo', 834),
('Books', 'PET Imag of Myocardium using Nitrogen 13', 835),
('Shoes', 'Supplement R Up Extrem Bursa/Lig w Nonaut Sub, Perc Endo', 836),
('Outdoors', 'Drainage of Right Acetabulum, Perc Endo Approach, Diagn', 837),
('Home', 'Supplement Left Foot Vein with Nonaut Sub, Perc Approach', 838),
('Baby', 'Excision of Urethra, Endo', 839),
('Beauty', 'Dilation of Left Foot Artery with 4 Drug-elut, Open Approach', 840),
('Baby', 'Insertion of Cardiac Lead into R Ventricle, Open Approach', 841),
('Electronics', 'Division of Right Lower Leg Tendon, Open Approach', 842),
('Electronics', 'Bypass R Verteb Vein to Up Vein w Synth Sub, Perc Endo', 843),
('Industrial', 'Bypass L Com Iliac Art to B Int Ilia w Autol Art, Perc Endo', 844),
('Industrial', 'Excision of Right Thorax Muscle, Perc Approach, Diagn', 845),
('Baby', 'Repair Left Abdomen Muscle, Open Approach', 846),
('Garden', 'Dilate L Ant Tib Art w 4+ Intralum Dev, Perc Endo', 847),
('Baby', 'Removal of Drainage Device from L Wrist Jt, Perc Approach', 848),
('Outdoors', 'Supplement L Int Mamm Art with Autol Sub, Perc Approach', 849),
('Kids', 'Bypass Accessory Pancreatic Duct to Duodenum, Open Approach', 850),
('Outdoors', 'Release Phrenic Nerve, Percutaneous Endoscopic Approach', 851),
('Automotive', 'Fluoroscopy of Left Hand', 852),
('Grocery', 'Insertion of Feeding Device into Ileum, Perc Approach', 853),
('Books', 'Dilation of Lower Artery with 4+ Intralum Dev, Open Approach', 854),
('Shoes', 'Alteration of Right Wrist Region, Percutaneous Approach', 855),
('Toys', 'Drainage of Pons with Drainage Device, Open Approach', 856),
('Books', 'Replace of R Tympanic Membrane with Autol Sub, Via Opening', 857),
('Books', 'Remove of Synth Sub from Prostate/Seminal Ves, Perc Approach', 858),
('Toys', 'Reposition Left Fibula with Intramed Fix, Open Approach', 859),
('Baby', 'Reposition Left Fibula with Intramed Fix, Perc Approach', 860),
('Toys', 'Repair Right 5th Toe, Percutaneous Approach', 861),
('Industrial', 'Hyperthermia of Pineal Body', 862),
('Books', 'Removal of Pressure Dressing on Left Lower Arm', 863),
('Health', 'Excision of Skull, Open Approach', 864),
('Books', 'Replacement of Right Rib with Autol Sub, Perc Endo Approach', 865),
('Books', 'Extirpate matter from R Com Iliac Vein, Perc Endo', 866),
('Toys', 'CT Scan of Bi Acromioclav Jt using Oth Contrast', 867),
('Industrial', 'Destruction of Left Tunica Vaginalis, Percutaneous Approach', 868),
('Sports', 'Extirpate matter from Head & Neck Tendon, Perc Endo', 869),
('Shoes', 'Bypass L Atrium to L Pulm Vn with Nonaut Sub, Open Approach', 870),
('Outdoors', 'Fusion Occip Jt w Synth Sub, Ant Appr A Col, Open', 871),
('Books', 'Supplement Ileum with Autol Sub, Perc Endo Approach', 872),
('Toys', 'Division of Neck Skin, External Approach', 873),
('Movies', 'Revision of Radioact Elem in Fem Perineum, Perc Approach', 874),
('Shoes', 'Restriction of Left Lacrimal Duct, Percutaneous Approach', 875),
('Electronics', 'Replacement of Finger Nail with Nonaut Sub, Extern Approach', 876),
('Baby', 'Measure of Arterial Saturation, Peripheral, Perc Approach', 877),
('Movies', 'Repair Right Peroneal Artery, Open Approach', 878),
('Automotive', 'Bypass R Verteb Vein to Up Vein w Autol Sub, Open', 879),
('Industrial', 'Insert Pace. Dual Cham in Abd Subcu/Fascia, Perc', 880),
('Jewelry', 'Release Acoustic Nerve, Open Approach', 881),
('Movies', 'Repair Small Intestine, Percutaneous Endoscopic Approach', 882),
('Music', 'HDR Brachytherapy of Abd Lymph using Iridium 192', 883),
('Computers', 'Extirpate matter from L Low Arm Subcu/Fascia, Perc', 884),
('Jewelry', 'Replacement of Pancreat Duct with Nonaut Sub, Open Approach', 885),
('Home', 'Dilation of R Hypogast Vein with Intralum Dev, Perc Approach', 886),
('Kids', 'Repair Left Lower Extremity Lymphatic, Open Approach', 887),
('Industrial', 'Lymphatic and Hemic Systems, Extraction', 888),
('Computers', 'Fluoroscopy of Bi Pelvic Vein using L Osm Contrast', 889),
('Jewelry', 'Revision of Intralum Dev in Great Vessel, Open Approach', 890),
('Automotive', 'Extirpation of Matter from R Maxillary Sinus, Open Approach', 891),
('Grocery', 'Supplement Right Hepatic Duct with Autol Sub, Perc Approach', 892),
('Movies', 'Revision of Int Fix in Lum Jt, Perc Endo Approach', 893),
('Industrial', 'Transfer Left Upper Leg Muscle with Skin, Perc Endo Approach', 894),
('Garden', 'Beam Radiation of Cervix using Electrons, Intraoperative', 895),
('Home', 'Release Left Hepatic Duct, Via Natural or Artificial Opening', 896),
('Beauty', 'Restriction of Gastric Art with Extralum Dev, Open Approach', 897),
('Kids', 'Supplement L Axilla Art with Autol Sub, Open Approach', 898),
('Health', 'Removal of Synthetic Substitute from Tracheobronc Tree, Endo', 899),
('Kids', 'Excision of L Metatarsotars Jt, Open Approach, Diagn', 900),
('Garden', 'Extraction of Products of Conception, Retained, Endo', 901),
('Electronics', 'Occlusion of Superior Vena Cava, Perc Endo Approach', 902),
('Music', 'Drainage of L Up Arm with Drain Dev, Perc Endo Approach', 903),
('Jewelry', 'Supplement L Thorax Bursa/Lig with Nonaut Sub, Open Approach', 904),
('Sports', 'Repair Eye in Products of Conception, Endo', 905),
('Garden', 'Restriction of Up Esophag with Intralum Dev, Open Approach', 906),
('Kids', 'Inspection of Cranial Nerve, Percutaneous Approach', 907),
('Books', 'Bypass R Popl Art to Low Ex Vein w Autol Vn, Perc Endo', 908),
('Grocery', 'Fluoroscopy of Epidural Veins', 909),
('Tools', 'Repair Left Orbit, Open Approach', 910),
('Books', 'Reposition Thor Jt with Int Fix, Perc Approach', 911),
('Sports', 'Revision of Monitoring Device in Spinal Canal, Perc Approach', 912),
('Clothing', 'Removal of Nonaut Sub from T-lum Jt, Open Approach', 913),
('Kids', 'Drainage of L Wrist Bursa/Lig, Perc Endo Approach, Diagn', 914),
('Music', 'Resection of Left Tympanic Membrane, Perc Endo Approach', 915),
('Grocery', 'Fusion of Left Knee Joint with Ext Fix, Perc Endo Approach', 916),
('Toys', 'Excision of Cervical Spinal Cord, Percutaneous Approach', 917),
('Movies', 'Fragmentation in Spinal Canal, External Approach', 918),
('Jewelry', 'Remove Synth Sub from L Finger Phalanx, Perc Endo', 919),
('Toys', 'Excision of Prostate, Perc Endo Approach, Diagn', 920),
('Sports', 'Dilation of Middle Esophagus, Percutaneous Approach', 921),
('Computers', 'Replace L Int Iliac Art w Synth Sub, Perc Endo', 922),
('Computers', 'Destruction of Right Palatine Bone, Perc Endo Approach', 923),
('Games', 'Introduction of Other Gas into GU Tract, Via Opening', 924),
('Outdoors', 'Extirpate matter from R Ext Auditory Canal, Extern', 925),
('Sports', 'Drainage of Cerv Jt with Drain Dev, Perc Approach', 926),
('Industrial', 'Fusion of >7 T Jt, Post Appr P Col, Open Approach', 927),
('Garden', 'LDR Brachytherapy of Salivary Gland using Californium 252', 928),
('Outdoors', 'Drainage of Left Carotid Body, Open Approach, Diagnostic', 929),
('Beauty', 'Bypass R Kidney Pelvis to Ileocutan w Synth Sub, Perc Endo', 930),
('Kids', 'Fusion Thor Jt w Intbd Fus Dev, Post Appr P Col, Perc', 931),
('Tools', 'Extraction of Upper Vein, Percutaneous Approach', 932),
('Sports', 'Bypass Left Subclavian Artery to L Pulm Art, Open Approach', 933),
('Clothing', 'Repair Genitalia Skin, External Approach', 934),
('Outdoors', 'Revision of Autol Sub in Cervcal Vertebra, Perc Approach', 935),
('Garden', 'Destruction of Esophagus, Via Natural or Artificial Opening', 936),
('Home', 'Dilate L Temporal Art, Bifurc, w Intralum Dev, Open', 937),
('Electronics', 'Bypass 3 Cor Art from L Int Mammary w Zooplastic, Perc Endo', 938),
('Music', 'Plaque Radiation of Ovary', 939),
('Baby', 'Insert Pace. Dual Cham in Abd Subcu/Fascia, Perc', 940),
('Kids', 'Revise Infusion Pump in Up Extrem Subcu/Fascia, Perc', 941),
('Industrial', 'Revision of Monitoring Device in Cranial Nrv, Perc Approach', 942),
('Movies', 'Reposition Left Elbow Joint, Open Approach', 943),
('Games', 'Destruction of Left Knee Tendon, Percutaneous Approach', 944),
('Kids', 'Dilation of 2 Cor Art, Bifurc, Perc Approach', 945),
('Jewelry', 'Bypass Left Ventricle to Cor Circ, Perc Endo Approach', 946),
('Music', 'Removal of Drain Dev from Cisterna Chyli, Open Approach', 947),
('Grocery', 'Extirpation of Matter from L Eustach Tube, Open Approach', 948),
('Baby', 'Inspection of Pleura, Percutaneous Approach', 949),
('Industrial', 'Revision of Spacer in Left Hip Joint, Open Approach', 950),
('Automotive', 'Removal of Int Fix from Coccyx, Open Approach', 951),
('Garden', 'Drainage of R Peroneal Art with Drain Dev, Open Approach', 952),
('Kids', 'Drainage of Right Upper Femur with Drain Dev, Open Approach', 953),
('Shoes', 'Revision of Intbd Fus Dev in Occip Jt, Perc Approach', 954),
('Clothing', 'Introduction of Oth Hormone into Periph Vein, Open Approach', 955),
('Health', 'Dilate of L Int Mamm Art with 4+ Intralum Dev, Perc Approach', 956),
('Baby', 'Inspection of Right Metacarpocarpal Joint, Open Approach', 957),
('Books', 'Division of Right Upper Arm Tendon, Perc Endo Approach', 958),
('Toys', 'Ultrasonography of Gallbladder and Bile Ducts', 959),
('Jewelry', 'Replace of L Abd Tendon with Nonaut Sub, Perc Endo Approach', 960),
('Health', 'Drainage of L Abd Bursa/Lig, Perc Endo Approach', 961),
('Jewelry', 'Bypass Trans Colon to Sigm Colon w Autol Sub, Open', 962),
('Industrial', 'Bypass Right Femoral Artery to Poplit Art, Open Approach', 963),
('Industrial', 'Dilation of L Int Iliac Art with 3 Drug-elut, Perc Approach', 964),
('Jewelry', 'Drainage of Right Hand Muscle, Percutaneous Approach, Diagn', 965),
('Music', 'Binaural Hearing Aid Assessment using Hear Aid Equipment', 966),
('Computers', 'Destruction of Left Toe Phalanx, Percutaneous Approach', 967),
('Health', 'Insertion of Radioactive Element into Resp Tract, Endo', 968),
('Sports', 'Destruction of Bilateral Lungs, Endo', 969),
('Music', 'Bypass R Com Iliac Art to B Ext Ilia, Open Approach', 970),
('Books', 'Bypass R Lacrml Duct to Nasal Cav w Synth Sub, Perc', 971),
('Movies', 'Release Right Shoulder Joint, Open Approach', 972),
('Health', 'Drainage of Perineum Tendon, Percutaneous Approach', 973),
('Beauty', 'Release Left Inferior Parathyroid Gland, Perc Approach', 974),
('Industrial', 'Supplement Thor Aorta Asc with Nonaut Sub, Open Approach', 975),
('Movies', 'Fusion R Metatarsophal Jt w Autol Sub, Perc Endo', 976),
('Kids', 'Extirpation of Matter from L Low Leg Muscle, Open Approach', 977),
('Kids', 'Drainage of R Elbow Bursa/Lig with Drain Dev, Open Approach', 978),
('Grocery', 'Repair Left Middle Finger, Percutaneous Approach', 979),
('Tools', 'Removal of Monitor Dev from Low Vein, Perc Endo Approach', 980),
('Grocery', 'Removal of Bandage on Neck', 981),
('Health', 'Revision of Drainage Device in Lower Muscle, Open Approach', 982),
('Automotive', 'Repair Right Femoral Vein, Open Approach', 983),
('Shoes', 'Bypass R Fem Art to Low Ex Art w Nonaut Sub, Open', 984),
('Clothing', 'Destruction of Bilateral Testes, Perc Endo Approach', 985),
('Grocery', 'Dilate of Face Art, Bifurc, with 2 Drug-elut, Open Approach', 986),
('Beauty', 'Restriction of L Pulm Vein with Extralum Dev, Perc Approach', 987),
('Shoes', 'Repair Lower Jaw, Open Approach', 988),
('Shoes', 'Revision of Synthetic Substitute in Up Intest Tract, Endo', 989),
('Automotive', 'Repair Left Maxilla, Percutaneous Endoscopic Approach', 990),
('Automotive', 'Transfer Acoustic Nerve to Hypogloss Nrv, Perc Endo Approach', 991),
('Automotive', 'Insertion of Infusion Device into GI Tract, Perc Approach', 992),
('Computers', 'Dilation of Right Pulmonary Vein, Open Approach', 993),
('Home', 'Revision of Autol Sub in Face, Perc Endo Approach', 994),
('Shoes', 'Ventil, Resp/Circ Assess Circ Low Back/LE w Mech Equip', 995),
('Automotive', 'Destruction of Left Hypogastric Vein, Percutaneous Approach', 996),
('Beauty', 'Beam Radiation of Pineal Body using Electrons, Intraop', 997),
('Baby', 'Division of Left Humeral Head, Open Approach', 998),
('Books', 'Insertion of Infusion Dev into R Ext Carotid, Perc Approach', 999),
('Baby', 'Drainage of Left External Carotid Artery, Perc Approach', 1000);

